## Learning Numpy

In [ ]:
import numpy as np

### creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D Array",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])

print("2D Array",arr_2d)


1D Array [1 2 3 4 5 6]
2D Array [[1 2 3]
 [4 5 6]]


### Difference Between List and Array Multiplication

In [ ]:
py_list = [1,2,3,4,5]
print("Python list multiplication, ",py_list*2)


np_array = np.array([1,2,3,4,5])
print("Python array multiplication ",np_array*2)


Python list multiplication,  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array multiplication  [ 2  4  6  8 10]


In [ ]:
import time
list_start = time.time()
py_list = [i*2 for i in range(10000000)]
list_end = time.time()
print("Time taken by list",list_end-list_start)

np_array_start = time.time()
np_array = np.arange(10000000)*2
np_array_end = time.time()
print("Time taken by array",np_array_end-np_array_start)


Time taken by list 0.7886011600494385
Time taken by array 0.03359055519104004


#### creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("Zero array\n",zeros)

one = np.ones((2,3))
print("One array\n",one)

full = np.full((2,3),7)
print("Full array\n",full)


random = np.random.random((2,3))
print("Random array\n",random*100)

sequence = np.arange(10,20,2)
print("Sequence array\n",sequence)

Zero array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array
 [[7 7 7]
 [7 7 7]]
Random array
 [[48.39825983 56.03476038 32.71023244]
 [86.1853192  43.16060881 82.99327986]]
Sequence array
 [10 12 14 16 18]


## Vector , Matrix and Tensor

In [ ]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([
    [[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]])
print("Tensor: \n",tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array Properties

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 4)
2
8
int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array: ",arr)

reshape = np.reshape(arr,(2,6))
print("\n Reshaped Array",reshape)

flatten = reshape.flatten()
print("\n Flattened Array",flatten)



# return view instead of copy that is it changes the structure of original array , not copys the original array
raveled = reshape.ravel()
print("\n Raveled Array",raveled)



Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Transpose
transpose = reshape.T
print("\n Transpose Array",transpose)


 Transpose Array [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')