## Numpy Array Operations

In [2]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
print("Basic Slicing ",arr[2:7])

print("With Step",arr[1:8:2])
print("With Negative indexing ",arr[-3])

Basic Slicing  [3 4 5 6 7]
With Step [2 4 6 8]
With Negative indexing  6


In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element ",arr_2d[1,2])
print("Specific Row",arr_2d[1])
print("Specific Column",arr_2d[:,2])

Specific Element  6
Specific Row [4 5 6]
Specific Column [3 6 9]


### Sorting

In [5]:
unsorted = np.array([2,5,31,1,7,9,23,1])
print("Unsorted Array ",unsorted)
print("Sorted Array ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[5,9],[0,8]])
print("Unsorted 2D Array ",arr_2d_unsorted)
print("Sorted 2D Array ",np.sort(arr_2d_unsorted,axis=1)) # Left to right
print("Sorted 2D Array ",np.sort(arr_2d_unsorted,axis=0)) # Top to bottom

Unsorted Array  [ 2  5 31  1  7  9 23  1]
Sorted Array  [ 1  1  2  5  7  9 23 31]
Unsorted 2D Array  [[3 1]
 [5 9]
 [0 8]]
Sorted 2D Array  [[1 3]
 [5 9]
 [0 8]]
Sorted 2D Array  [[0 1]
 [3 8]
 [5 9]]


## Filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers =numbers[numbers %2 == 0]
print("Even numbers: ",even_numbers)

Even numbers:  [ 2  4  6  8 10]


## Filter with Mask

In [7]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing Vs np.where()

In [8]:
indics = [0,1,2]
print(numbers[indics])

where_indics = np.where(numbers > 5)
print(numbers[where_indics])

[1 2 3]
[ 6  7  8  9 10]


In [9]:
conditon_array = np.where(numbers>5,numbers*4,numbers)
print(conditon_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [10]:
# if(numbers >5 ):
#   numbers*4
# else:
#   numbers
#  This is same as np.where(numbers>5,numbers*4,numbers)

In [12]:
conditon_array = np.where(numbers>5,True,False)
print(conditon_array)

[False False False False False  True  True  True  True  True]


## Adding and Removing Data

In [13]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([11,12,13,14,15,16,17,18,19,20])
print("Concatenated Array ",np.concatenate((arr1,arr2)))

Concatenated Array  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Array Compatibility


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility shapes",a.shape == b.shape)

Compatibility shapes True


In [17]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
print(original)
print("With New Row \n",with_new_row)

new_col = np.array([[7],[4]])
with_new_col = np.hstack((original,new_col))
print("With New Column \n",with_new_col)


[[1 2]
 [3 4]]
With New Row 
 [[1 2]
 [3 4]
 [5 6]]
With New Column 
 [[1 2 7]
 [3 4 4]]


### Delete Operations

In [18]:
arr = np.array([1,2,3,4,5,6,7,8])
deleted =np.delete(arr,2)
print("Deleted Array ",deleted)

Deleted Array  [1 2 4 5 6 7 8]
